export {Home} from './Home';
export {Admin} from './Admin';
export {PageNotFound} from './PageNotFound';
export {ProductDetail} from './ProductDetail';
export {ProductList} from './ProductList';
export {Contact} from './contact/Contact';
export {ContactIn} from './contact/ContactIn';
export {ContactUs} from './contact/ContactUs';
export {ContactOther} from './contact/ContactOther';
